import { type NextPage } from 'next'
import Head from 'next/head'
import axios from 'axios'
import { useEffect } from 'react'
import { serialize, stringify } from 'superjson'
import { Form } from '@/pgen/frontend/users/forms'

import Link from 'next/link'

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Form />
    </>
  )
}

export default Page

