import { type NextPage } from 'next'
import Head from 'next/head'
import axios from 'axios'
import { useEffect } from 'react'
import { serialize, stringify } from 'superjson'

import Link from 'next/link'

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#ff5555] to-[#ff9999]'>
        <div className='container flex flex-col items-center justify-center gap-12 px-4 py-16 '>
          <h1 className='text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]'>
            Prisma-Generator-Next
          </h1>
          <div className='grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8'>
            <Link
              className='flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20'
              href='https://create.t3.gg/en/usage/first-steps'
              target='_blank'
            >
              <h3 className='text-2xl font-bold'>Models</h3>
              <div className='text-lg'>View your models</div>
            </Link>
            <Link
              className='flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20'
              href='https://create.t3.gg/en/introduction'
              target='_blank'
            >
              <h3 className='text-2xl font-bold'>Api Routes</h3>
              <div className='text-lg'>See api route examples</div>
            </Link>
          </div>
        </div>
      </main>
    </>
  )
}

export default Page
