import { type NextPage } from 'next'
import Head from 'next/head'
import { Pform } from '@/pgen/frontend/users/p-form'

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Pform />
    </>
  )
}

export default Page


